name: DevSecOps Security Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  # -------------------
  # SAST & SCA
  # -------------------
  security-scan-sast-sca:
    name: SAST & SCA Scans
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Semgrep SAST
        uses: returntocorp/semgrep-action@v1
        with:
          config: auto

      - name: Run Snyk Test (show vulnerabilities without failing)
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          json: false
        continue-on-error: true

      - name: Run Snyk Monitor (Dashboard)
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "requirements.txt not found, skipping pip install"
          fi

  # -------------------
  # DAST (ZAP)
  # -------------------
  zap_scan:
    name: DAST Scan (ZAP)
    runs-on: ubuntu-latest
    needs: security-scan-sast-sca
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start Vampi service
        run: |
          docker run -d --name vampi -p 5000:5000 erev0s/vampi:latest
          echo "Waiting 10 seconds for service to start..."
          sleep 10

      - name: Prepare ZAP workspace
        run: |
         mkdir -p $PWD/zap-temp
         chmod 777 $PWD/zap-temp

      - name: Run ZAP Baseline Scan
        run: |
         docker run --rm \
          --network host \
          -v $PWD/zap-temp:/zap/wrk \
          ghcr.io/zaproxy/zaproxy:stable \
          zap.sh -cmd -quickurl http://localhost:5000 -quickout /zap/wrk/zap_report.html

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-temp/zap_report.html